# Generated by Django 4.2.9 on 2024-01-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="imageinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_title", models.CharField(default=None, max_length=50)),
                ("number_of_images", models.IntegerField(default=2)),
                ("input_image", models.ImageField(upload_to="inputimages")),
            ],
        ),
    ]
