# Generated by Django 4.2.9 on 2024-01-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="zipinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_title", models.CharField(default=None, max_length=50)),
                ("number_of_images", models.IntegerField(default=2)),
                ("input_image", models.FileField(upload_to="inputzip")),
            ],
        ),
    ]
