# Generated by Django 4.2.9 on 2024-01-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0002_zipinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zipinfo",
            old_name="input_image",
            new_name="input_zip",
        ),
    ]
