# Generated by Django 4.2.9 on 2024-02-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0003_rename_input_image_zipinfo_input_zip"),
    ]

    operations = [
        migrations.CreateModel(
            name="multiImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_title", models.CharField(default=None, max_length=50)),
                ("number_of_folders", models.IntegerField(default=2)),
                ("input_image", models.ImageField(upload_to="multiple")),
            ],
        ),
    ]
