# Generated by Django 4.2.9 on 2024-02-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0004_multiimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiimg",
            name="input_image",
            field=models.ImageField(upload_to="multipleImage"),
        ),
    ]
